### ISSUE TITLE
Include .blend file of skinned mesh

### ISSUE THREAD

**Issue by franklinblanco** [Kurble/bevy_mod_inverse_kinematics#1]
Hello! I firstly want to thank you for your work with this crate. 
It's my last hope at using IK with bevy before just going back to animating x^n animations for every character.
So I wanted to ask you if possible to put up the .blend file you used for exporting the skin.gltf asset. I ask for this to know how to rig the character I have so that it works with your system!

I put in all the bone names correctly and it even moves the bone transforms correctly, but no meshes move with the bones due to my rig not being configured correctly for bevy.

Thank you a lot for your work once again.

**Comment by Kurble** [comment]
I don't really want to share my .blend file, as I might want to use it for my own projects some time. (You can still do whatever you want with the .gltf asset)

The rig should work in bevy if the bones are attached to the mesh in the gltf asset. Needless to say, the skinning needs to at least work in blender so make sure you got that right.

This is my outline in blender:
![image](https://github.com/Kurble/bevy_mod_inverse_kinematics/assets/1321421/e72a79df-cecb-4cb5-9ca1-ba42b2996442)
The mesh should have an "Armature" modifier that points to your skeleton, and if you've done it the right way blender will generate vertex groups for you that bind the vertices to the different bones (weighting)
