### ISSUE TITLE
Issues with mixamo models

### ISSUE THREAD

**Issue by joscha-alisch** [Kurble/bevy_mod_inverse_kinematics#2]
Hey there! Tried this out with a couple of character models from [mixamo.com ](https://www.mixamo.com)- e.g. "X-bot". Unfortunately, I run into the issue that something seems to go wrong with the inverse kinematics. See below for a comparison between your model and the one I'm using. Yours works perfectly well, which makes me believe that the integration of the plugin into my codebase works fine. Also, regular animations exported from Blender work, so the skeleton itself appears to work fine inside Bevy.

<img width="794" alt="Screenshot 2024-01-07 at 21 07 18" src="https://github.com/Kurble/bevy_mod_inverse_kinematics/assets/9500791/0e631e67-1837-4490-983e-3f498f2ce291">

I compared the skeletons in Blender and at least I couldn't figure out any major differences.  Do you have any pointers on where I could further investigate this?

**Comment by joscha-alisch** [comment]
Figured it out - for some reason, the mixamo models come with a scale of `0.01` which seems to break either something in bevy in regards to the bone positions, or in the algorithms of this crate. Anyways, applying all transforms in blender and then re-exporting fixed the issue.

**Comment by rparrett** [comment]
Just wanted to say thanks for documenting the issue and fix!
